version: 0.2
env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: 349110610264.dkr.ecr.ap-south-1.amazonaws.com
    CLUSTER_NAME: demo-cluster-1
phases:
  install:
     commands: 
      - curl -o /usr/local/bin/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x /usr/local/bin/kubectl
      - kubectl version --client
      - echo "Installing eksctl..."
      - curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
      - tar xz -C /usr/local/bin -f eksctl_$(uname -s)_amd64.tar.gz
      - eksctl version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - docker build -t webapp .
      - docker tag webapp:latest $ECR_REPO/webapp:latest
      - docker push $ECR_REPO/webapp:latest
      - echo Image built and pushed to ECR
  
  post_build:
    commands:
      - echo Deploying to EKS cluster...
      - cd ./k8s
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - echo "Verifying access..."
      - kubectl get ns || echo "Kubeconfig working!"
      - kubectl get ns webapp || kubectl create namespace webapp
      - kubectl apply -f k8s-aws.yaml
      - echo Deployment to EKS completed...
      - kubectl get pods -n webapp
      - kubectl get svc -n webapp                                                                                        